/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sotwtm_ocr_demo_jni_JniBitmapUtil */

#ifndef _Included_com_sotwtm_ocr_demo_jni_JniBitmapUtil
#define _Included_com_sotwtm_ocr_demo_jni_JniBitmapUtil
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT void JNICALL Java_com_sotwtm_ocr_demo_jni_JniBitmapUtil_decode(JNIEnv *env, jclass javaClass, jobject target, jbyteArray source);
#ifdef __cplusplus
}
#endif
#endif
